### ISSUE TITLE
Yo

### ISSUE THREAD

**Issue by ghost** [dontbanmeplz/python#1]
You can code right?

Cuz that CrimsonWare token grabber isnt for Discord. It's for WikiMedia.

Why would you make it require discord.js for a program that isnt even for Discord

**Comment by dontbanmeplz** [comment]
I didnt do that i just made a joke about borrowing.
Also con you send me your discord server, the invite expired

**Comment by dontbanmeplz** [comment]
Actually in the original commit **you** put the dependency in

**Comment by ghost** [comment]
o shittttttt. ye mane im dum

**Comment by dontbanmeplz** [comment]
Lmao
